export const weatherIconMap: { [key: string]: string } = {
  Thunderstorm: "ri-thunderstorms-line",
  Drizzle: "ri-drizzle-line",
  Rain: "ri-rainy-line",
  Snow: "ri-snowy-line",
  Mist: "ri-foggy-line",
  Smoke: "ri-smoke-line",
  Haze: "ri-haze-line",
  Dust: "ri-dust-line",
  Fog: "ri-foggy-line",
  Sand: "ri-sandstorm-line",
  Ash: "ri-volcano-line",
  Squall: "ri-windy-line",
  Tornado: "ri-tornado-line",
  Clear: "ri-sun-line",
  Clouds: "ri-cloudy-line",
};
